apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: haj8wbvuk-python
  janus-idp.io/tekton: haj8wbvuk-python
  backstage.io/kubernetes-id: haj8wbvuk-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: haj8wbvuk-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
