apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: haj8wbvuk-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: haj8wbvuk-python 
  name: haj8wbvuk-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: haj8wbvuk-python 
